apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
  labels:
    app: vprodb
spec:
  selector:
    matchLabels:
      app: vprodb
  replicas: 1
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      containers:
      - name: vprodb
        image: smartronak2912/vprofiledb-mysql:V1
        args:
          - "ignore-db-dir=lost+found"
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: vpro-db-data
        ports:
        - containerPort: 3306
          name: vprodb-port
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: db-pass
      nodeSelector:
        zone: ca-central-1a
      volumes:
        - name: vpro-db-data
          awsElasticBlockStore:
            volumeID: vol-00981a2c0eb1061a8
            fsType: ext4

        
    
        
